"""
HutchSolves — Cortex Branding Constants
Deep Ocean colour scheme (Cyan / Teal).
"""

from reportlab.lib.colors import HexColor

# ── Palette ───────────────────────────────────────────────────────────────────
DEEP_OCEAN_PRIMARY   = HexColor("#0097A7")   # Deep Cyan-Teal
DEEP_OCEAN_SECONDARY = HexColor("#00BCD4")   # Bright Cyan
DEEP_OCEAN_ACCENT    = HexColor("#004D5C")   # Dark Teal (headings, rules)
DEEP_OCEAN_LIGHT     = HexColor("#E0F7FA")   # Ice (section backgrounds)
DEEP_OCEAN_TEXT      = HexColor("#1A2E35")   # Near-black readable text
WHITE                = HexColor("#FFFFFF")
PULSE_HEALTHY        = HexColor("#26A69A")   # Teal green
PULSE_DRIFTING       = HexColor("#FFA726")   # Amber
PULSE_CRITICAL       = HexColor("#EF5350")   # Red

# ── Typography ────────────────────────────────────────────────────────────────
FONT_TITLE   = "Helvetica-Bold"
FONT_HEADING = "Helvetica-Bold"
FONT_BODY    = "Helvetica"
FONT_CAPTION = "Helvetica-Oblique"

# ── Identity ──────────────────────────────────────────────────────────────────
BRAND_NAME     = "HutchSolves"
SUITE_NAME     = "HutchSolves Suite"
PRODUCT_NAME   = "Cortex — Flow & Grow"
REPORT_TITLE   = "Client Drift & Growth Report"
FOOTER_TEXT    = "Confidential — Generated by HutchSolves Cortex"
WATERMARK_TEXT = "HutchSolves Suite"


def pulse_color(pulse: str) -> HexColor:
    """Return the badge colour for a given Systems Pulse status."""
    return {
        "HEALTHY":  PULSE_HEALTHY,
        "DRIFTING": PULSE_DRIFTING,
        "CRITICAL": PULSE_CRITICAL,
    }.get(pulse.upper(), PULSE_CRITICAL)
